version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: v-place2-app
    volumes:
      - /home/valalol/vplace2:/app/tmp
    ports:
      - "8082:3333"
    env_file:
      - stack.env
    restart: unless-stopped
networks:
  default:
    external:
      name: npm-net