version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: v-place2-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped